const actions = {
    SET_ORIGIN: 'SET_ORIGIN',
    SET_SCHEDULED_ORIGIN: 'SET_SCHEDULED_ORIGIN',
    SET_DESTINATION: 'SET_DESTINATION',
    SET_FLIGHT: 'SET_FLIGHT',
    SET_SCHEDULE: 'SET_SCHEDULE',
    SET_PAGES: 'SET_PAGES',
    SET_DESTINATIONS: 'SET_DESTINATIONS',
    RESET_DATA: 'RESET_DATA',
    SET_ATTRIBUTE_ELEMENTS: 'SET_ATTRIBUTE_ELEMENTS',
    SET_ROUTE: 'SET_ROUTE',
    SET_REPORT: 'SET_REPORT',
    SET_USER: 'SET_USER',
    SET_CARRIER: 'SET_CARRIER',
    SET_CARRIER_CODES_IN_SEARCH_RESULT: 'SET_CARRIER_CODES_IN_SEARCH_RESULT'
};

export default actions;