const actions = {
    SET_ORIGIN: 'SET_ORIGIN',
    SET_SCHEDULED_ORIGIN: 'SET_SCHEDULED_ORIGIN',
    SET_DESTINATION: 'SET_DESTINATION',
    SET_FLIGHT: 'SET_FLIGHT',
    SET_SCHEDULE: 'SET_SCHEDULE',
    SET_PAGES: 'SET_PAGES',
    SET_DESTINATIONS: 'SET_DESTINATIONS',
    RESET_DATA: 'RESET_DATA'
};

export default actions;