let airports =
    {
        ACK: {
            name: 'Nantucket Memorial Airport',
            city: 'Nantucket',
            state: 'MA',
            country: 'United States',
            carriers: 6,
            flights: 9,
            tz: 'America/New_York',
            lat: 41.25310135,
            lon: -70.06020355
        },
        ACV: {
            name: 'Arcata Airport',
            city: 'Arcata CA',
            state: 'CA',
            country: 'United States',
            carriers: 7,
            flights: 6,
            tz: 'America/Los_Angeles',
            lat: 40.97809982,
            lon: -124.1090012
        },
        ALO: {
            name: 'Waterloo Regional Airport',
            city: 'Waterloo',
            state: 'IA',
            country: 'United States',
            carriers: 4,
            flights: 1,
            tz: 'America/Chicago',
            lat: 42.55709839,
            lon: -92.40029907
        },
        ATL: {
            name: 'Hartsfield Jackson Atlanta International Airport',
            city: 'Atlanta',
            state: 'GA',
            country: 'United States',
            carriers: 60,
            flights: 253,
            tz: 'America/New_York',
            lat: 33.63669968,
            lon: -84.42810059
        },
        BET: {
            name: 'Bethel Airport',
            city: 'Bethel',
            state: 'AK',
            country: 'United States',
            carriers: 11,
            flights: 29,
            tz: 'America/Anchorage',
            lat: 60.77980042,
            lon: -161.8379974
        },
        BGR: {
            name: 'Bangor International Airport',
            city: 'Bangor',
            state: 'ME',
            country: 'United States',
            carriers: 7,
            flights: 10,
            tz: 'America/New_York',
            lat: 44.80739975,
            lon: -68.82810211
        },
        BHM: {
            name: 'Birmingham-Shuttlesworth International Airport',
            city: 'Birmingham',
            state: 'AL',
            country: 'United States',
            carriers: 24,
            flights: 34,
            tz: 'America/Chicago',
            lat: 33.56290054,
            lon: -86.75350189
        },
        BIL: {
            name: 'Billings Logan International Airport',
            city: 'Billings',
            state: 'MT',
            country: 'United States',
            carriers: 14,
            flights: 13,
            tz: 'America/Denver',
            lat: 45.80770111,
            lon: -108.5429993
        },
        BQK: {
            name: 'Brunswick Golden Isles Airport',
            city: 'Brunswick',
            state: 'GA',
            country: 'United States',
            carriers: 2,
            flights: 1,
            tz: 'America/New_York',
            lat: 31.25880051,
            lon: -81.46649933
        },
        BQN: {
            name: 'Rafael Hernandez Airport',
            city: 'Aguadilla',
            state: 'PR',
            country: 'Puerto Rico',
            carriers: 5,
            flights: 4,
            tz: 'America/Puerto_Rico',
            lat: 18.49489975,
            lon: -67.12940216
        },
        BUR: {
            name: 'Bob Hope Airport',
            city: 'Burbank',
            state: 'CA',
            country: 'United States',
            carriers: 12,
            flights: 14,
            tz: 'America/Los_Angeles',
            lat: 34.20069885,
            lon: -118.3590012
        },
        CAK: {
            name: 'Akron Canton Regional Airport',
            city: 'Akron',
            state: 'OH',
            country: 'United States',
            carriers: 13,
            flights: 13,
            tz: 'America/New_York',
            lat: 40.91609955,
            lon: -81.44219971
        },
        CHS: {
            name: 'Charleston Air Force Base-International Airport',
            city: 'Charleston',
            state: 'SC',
            country: 'United States',
            carriers: 25,
            flights: 22,
            tz: 'America/New_York',
            lat: 32.89860153,
            lon: -80.04049683
        },
        CIU: {
            name: 'Chippewa County International Airport',
            city: 'Sault Ste Marie',
            state: 'MI',
            country: 'United States',
            carriers: 4,
            flights: 2,
            tz: 'America/New_York',
            lat: 46.25080109,
            lon: -84.47239685
        },
        COS: {
            name: 'City of Colorado Springs Municipal Airport',
            city: 'Colorado Springs',
            state: 'CO',
            country: 'United States',
            carriers: 19,
            flights: 16,
            tz: 'America/Denver',
            lat: 38.80580139,
            lon: -104.7009964
        },
        COU: {
            name: 'Columbia Regional Airport',
            city: 'Columbia',
            state: 'MO',
            country: 'United States',
            carriers: 4,
            flights: 3,
            tz: 'America/Chicago',
            lat: 38.81809998,
            lon: -92.21959686
        },
        CPR: {
            name: 'Casper-Natrona County International Airport',
            city: 'Casper',
            state: 'WY',
            country: 'United States',
            carriers: 4,
            flights: 4,
            tz: 'America/Denver',
            lat: 42.90800095,
            lon: -106.4639969
        },
        DEN: {
            name: 'Denver International Airport',
            city: 'Denver',
            state: 'CO',
            country: 'United States',
            carriers: 57,
            flights: 162,
            tz: 'America/Denver',
            lat: 39.86169815,
            lon: -104.6729965
        },
        DSM: {
            name: 'Des Moines International Airport',
            city: 'Des Moines',
            state: 'IA',
            country: 'United States',
            carriers: 24,
            flights: 20,
            tz: 'America/Chicago',
            lat: 41.5340004,
            lon: -93.6631012
        },
        EAU: {
            name: 'Chippewa Valley Regional Airport',
            city: 'Eau Claire',
            state: 'WI',
            country: 'United States',
            carriers: 5,
            flights: 3,
            tz: 'America/Chicago',
            lat: 44.86579895,
            lon: -91.48429871
        },
        EGE: {
            name: 'Eagle County Regional Airport',
            city: 'Vail',
            state: 'CO',
            country: 'United States',
            carriers: 9,
            flights: 12,
            tz: 'America/Denver',
            lat: 39.64260101,
            lon: -106.9179993
        },
        EWN: {
            name: 'Coastal Carolina Regional Airport',
            city: 'New Bern',
            state: 'NC',
            country: 'United States',
            carriers: 4,
            flights: 3,
            tz: 'America/New_York',
            lat: 35.07300186,
            lon: -77.04290009
        },
        EYW: {
            name: 'Key West International Airport',
            city: 'Key West',
            state: 'FL',
            country: 'United States',
            carriers: 10,
            flights: 8,
            tz: 'America/New_York',
            lat: 24.55610085,
            lon: -81.75959778
        },
        FAR: {
            name: 'Hector International Airport',
            city: 'Fargo',
            state: 'ND',
            country: 'United States',
            carriers: 12,
            flights: 7,
            tz: 'America/Chicago',
            lat: 46.92070007,
            lon: -96.81580353
        },
        FAY: {
            name: 'Fayetteville Regional Grannis Field',
            city: 'Fayetteville',
            state: 'NC',
            country: 'United States',
            carriers: 6,
            flights: 2,
            tz: 'America/New_York',
            lat: 34.99119949,
            lon: -78.88030243
        },
        FSM: {
            name: 'Fort Smith Regional Airport',
            city: 'Fort Smith',
            state: 'AR',
            country: 'United States',
            carriers: 5,
            flights: 3,
            tz: 'America/Chicago',
            lat: 35.33660126,
            lon: -94.36740112
        },
        FWA: {
            name: 'Fort Wayne International Airport',
            city: 'Fort Wayne',
            state: 'IN',
            country: 'United States',
            carriers: 16,
            flights: 27,
            tz: 'America/New_York',
            lat: 40.97850037,
            lon: -85.19509888
        },
        GCC: {
            name: 'Gillette Campbell County Airport',
            city: 'Gillette',
            state: 'WY',
            country: 'United States',
            carriers: 4,
            flights: 4,
            tz: 'America/Denver',
            lat: 44.34889984,
            lon: -105.5390015
        },
        GFK: {
            name: 'Grand Forks International Airport',
            city: 'Grand Forks',
            state: 'ND',
            country: 'United States',
            carriers: 5,
            flights: 3,
            tz: 'America/Chicago',
            lat: 47.949299,
            lon: -97.176102
        },
        GJT: {
            name: 'Grand Junction Regional Airport',
            city: 'Grand Junction',
            state: 'CO',
            country: 'United States',
            carriers: 11,
            flights: 7,
            tz: 'America/Denver',
            lat: 39.12239838,
            lon: -108.5270004
        },
        GPT: {
            name: 'Gulfport Biloxi International Airport',
            city: 'Gulfport',
            state: 'MS',
            country: 'United States',
            carriers: 11,
            flights: 9,
            tz: 'America/Chicago',
            lat: 30.40730095,
            lon: -89.07009888
        },
        HDN: {
            name: 'Yampa Valley Airport',
            city: 'Hayden',
            state: 'CO',
            country: 'United States',
            carriers: 8,
            flights: 9,
            tz: 'America/Denver',
            lat: 40.48120117,
            lon: -107.2180023
        },
        HIB: {
            name: 'Range Regional Airport',
            city: 'Hibbing',
            state: 'MN',
            country: 'United States',
            carriers: 3,
            flights: 2,
            tz: 'America/Chicago',
            lat: 47.38660049,
            lon: -92.83899689
        },
        HLN: {
            name: 'Helena Regional Airport',
            city: 'Helena',
            state: 'MT',
            country: 'United States',
            carriers: 8,
            flights: 6,
            tz: 'America/Denver',
            lat: 46.60680008,
            lon: -111.9830017
        },
        HOB: {
            name: 'Lea County Regional Airport',
            city: 'Hobbs',
            state: 'NM',
            country: 'United States',
            carriers: 1,
            flights: 1,
            tz: 'America/Denver',
            lat: 32.6875,
            lon: -103.2170029
        },
        HYS: {
            name: 'Hays Regional Airport',
            city: 'Hays',
            state: 'KS',
            country: 'United States',
            carriers: 3,
            flights: 2,
            tz: 'America/Chicago',
            lat: 38.84220123,
            lon: -99.27320099
        },
        IDA: {
            name: 'Idaho Falls Regional Airport',
            city: 'Idaho Falls',
            state: 'ID',
            country: 'United States',
            carriers: 8,
            flights: 6,
            tz: 'America/Denver',
            lat: 43.51459885,
            lon: -112.0709991
        },
        IND: {
            name: 'Indianapolis International Airport',
            city: 'Indianapolis',
            state: 'IN',
            country: 'United States',
            carriers: 39,
            flights: 46,
            tz: 'America/New_York',
            lat: 39.7173,
            lon: -86.294403
        },
        ITH: {
            name: 'Ithaca Tompkins Regional Airport',
            city: 'Ithaca',
            state: 'NY',
            country: 'United States',
            carriers: 6,
            flights: 5,
            tz: 'America/New_York',
            lat: 42.49100113,
            lon: -76.45839691
        },
        LAN: {
            name: 'Capital City Airport',
            city: 'Lansing',
            state: 'MI',
            country: 'United States',
            carriers: 7,
            flights: 5,
            tz: 'America/New_York',
            lat: 42.77870178,
            lon: -84.58740234
        },
        LAR: {
            name: 'Laramie Regional Airport',
            city: 'Laramie',
            state: 'WY',
            country: 'United States',
            carriers: 3,
            flights: 2,
            tz: 'America/Denver',
            lat: 41.31209946,
            lon: -105.6750031
        },
        LAS: {
            name: 'McCarran International Airport',
            city: 'Las Vegas',
            state: 'NV',
            country: 'United States',
            carriers: 64,
            flights: 130,
            tz: 'America/Los_Angeles',
            lat: 36.08010101,
            lon: -115.1520004
        },
        LAW: {
            name: 'Lawton Fort Sill Regional Airport',
            city: 'Lawton',
            state: 'OK',
            country: 'United States',
            carriers: 3,
            flights: 2,
            tz: 'America/Chicago',
            lat: 34.56769943,
            lon: -98.41660309
        },
        LCH: {
            name: 'Lake Charles Regional Airport',
            city: 'Lake Charles',
            state: 'LA',
            country: 'United States',
            carriers: 5,
            flights: 1,
            tz: 'America/Chicago',
            lat: 30.12610054,
            lon: -93.22329712
        },
        LEX: {
            name: 'Blue Grass Airport',
            city: 'Lexington KY',
            state: 'KY',
            country: 'United States',
            carriers: 17,
            flights: 14,
            tz: 'America/New_York',
            lat: 38.03649902,
            lon: -84.60590363
        },
        LIT: {
            name: 'Bill & Hillary Clinton National Airport/Adams Field',
            city: 'Little Rock',
            state: 'AR',
            country: 'United States',
            carriers: 20,
            flights: 22,
            tz: 'America/Chicago',
            lat: 34.72940063,
            lon: -92.22429657
        },
        LNK: {
            name: 'Lincoln Airport',
            city: 'Lincoln',
            state: 'NE',
            country: 'United States',
            carriers: 9,
            flights: 5,
            tz: 'America/Chicago',
            lat: 40.85100174,
            lon: -96.75920105
        },
        LSE: {
            name: 'La Crosse Municipal Airport',
            city: 'La Crosse',
            state: 'WI',
            country: 'United States',
            carriers: 7,
            flights: 3,
            tz: 'America/Chicago',
            lat: 43.879002,
            lon: -91.256699
        },
        MCI: {
            name: 'Kansas City International Airport',
            city: 'Kansas City',
            state: 'MO',
            country: 'United States',
            carriers: 41,
            flights: 64,
            tz: 'America/Chicago',
            lat: 39.2976,
            lon: -94.713898
        },
        MDW: {
            name: 'Chicago Midway International Airport',
            city: 'Chicago',
            state: 'IL',
            country: 'United States',
            carriers: 8,
            flights: 55,
            tz: 'America/Chicago',
            lat: 41.7859993,
            lon: -87.75240326
        },
        MEM: {
            name: 'Memphis International Airport',
            city: 'Memphis',
            state: 'TN',
            country: 'United States',
            carriers: 28,
            flights: 96,
            tz: 'America/Chicago',
            lat: 35.04240036,
            lon: -89.97669983
        },
        MQT: {
            name: 'Sawyer International Airport',
            city: 'Gwinn',
            state: 'MI',
            country: 'United States',
            carriers: 6,
            flights: 5,
            tz: 'America/New_York',
            lat: 46.35359955,
            lon: -87.395401
        },
        MSP: {
            name: 'Minneapolis-St Paul International/Wold-Chamberlain Airport',
            city: 'Minneapolis',
            state: 'MN',
            country: 'United States',
            carriers: 41,
            flights: 171,
            tz: 'America/Chicago',
            lat: 44.88199997,
            lon: -93.22180176
        },
        MSY: {
            name: 'Louis Armstrong New Orleans International Airport',
            city: 'New Orleans',
            state: 'LA',
            country: 'United States',
            carriers: 44,
            flights: 41,
            tz: 'America/Chicago',
            lat: 29.99340057,
            lon: -90.25800323
        },
        MTJ: {
            name: 'Montrose Regional Airport',
            city: 'Montrose CO',
            state: 'CO',
            country: 'United States',
            carriers: 8,
            flights: 8,
            tz: 'America/Denver',
            lat: 38.50979996,
            lon: -107.8939972
        },
        OAJ: {
            name: 'Albert J Ellis Airport',
            city: 'Jacksonville NC',
            state: 'NC',
            country: 'United States',
            carriers: 3,
            flights: 2,
            tz: 'America/New_York',
            lat: 34.82920074,
            lon: -77.61209869
        },
        OGG: {
            name: 'Kahului Airport',
            city: 'Kahului',
            state: 'HI',
            country: 'United States',
            carriers: 19,
            flights: 20,
            tz: 'Pacific/Honolulu',
            lat: 20.89859962,
            lon: -156.4299927
        },
        OKC: {
            name: 'Will Rogers World Airport',
            city: 'Oklahoma City',
            state: 'OK',
            country: 'United States',
            carriers: 28,
            flights: 29,
            tz: 'America/Chicago',
            lat: 35.39310074,
            lon: -97.60070038
        },
        ORF: {
            name: 'Norfolk International Airport',
            city: 'Norfolk',
            state: 'VA',
            country: 'United States',
            carriers: 27,
            flights: 28,
            tz: 'America/New_York',
            lat: 36.89459991,
            lon: -76.20120239
        },
        OTZ: {
            name: 'Ralph Wien Memorial Airport',
            city: 'Kotzebue',
            state: 'AK',
            country: 'United States',
            carriers: 8,
            flights: 13,
            tz: 'America/Anchorage',
            lat: 66.88469696,
            lon: -162.598999
        },
        PBG: {
            name: 'Plattsburgh International Airport',
            city: 'Plattsburgh',
            state: 'NY',
            country: 'United States',
            carriers: 2,
            flights: 3,
            tz: 'America/New_York',
            lat: 44.65090179,
            lon: -73.4681015
        },
        PHX: {
            name: 'Phoenix Sky Harbor International Airport',
            city: 'Phoenix',
            state: 'AZ',
            country: 'United States',
            carriers: 51,
            flights: 108,
            tz: 'America/Phoenix',
            lat: 33.43429947,
            lon: -112.012001
        },
        PIB: {
            name: 'Hattiesburg Laurel Regional Airport',
            city: 'Hattiesburg/Laurel',
            state: 'MS',
            country: 'United States',
            carriers: 2,
            flights: 1,
            tz: 'America/Chicago',
            lat: 31.46710014,
            lon: -89.33709717
        },
        PIH: {
            name: 'Pocatello Regional Airport',
            city: 'Pocatello',
            state: 'ID',
            country: 'United States',
            carriers: 1,
            flights: 1,
            tz: 'America/Denver',
            lat: 42.90980148,
            lon: -112.5960007
        },
        PSE: {
            name: 'Mercedita Airport',
            city: 'Ponce',
            state: 'PR',
            country: 'Puerto Rico',
            carriers: 4,
            flights: 4,
            tz: 'America/Puerto_Rico',
            lat: 18.00830078,
            lon: -66.56300354
        },
        PSG: {
            name: 'Petersburg James A Johnson Airport',
            city: 'Petersburg',
            state: 'AK',
            country: 'United States',
            carriers: 3,
            flights: 2,
            tz: 'America/Anchorage',
            lat: 56.80170059,
            lon: -132.9450073
        },
        RIC: {
            name: 'Richmond International Airport',
            city: 'Richmond',
            state: 'VA',
            country: 'United States',
            carriers: 34,
            flights: 26,
            tz: 'America/New_York',
            lat: 37.50519943,
            lon: -77.31970215
        },
        ROA: {
            name: 'Roanokeâ€“Blacksburg Regional Airport',
            city: 'Roanoke VA',
            state: 'VA',
            country: 'United States',
            carriers: 18,
            flights: 13,
            tz: 'America/New_York',
            lat: 37.32550049,
            lon: -79.97540283
        },
        RST: {
            name: 'Rochester International Airport',
            city: 'Rochester',
            state: 'MN',
            country: 'United States',
            carriers: 9,
            flights: 6,
            tz: 'America/Chicago',
            lat: 43.90829849,
            lon: -92.5
        },
        RSW: {
            name: 'Southwest Florida International Airport',
            city: 'Fort Myers',
            state: 'FL',
            country: 'United States',
            carriers: 25,
            flights: 39,
            tz: 'America/New_York',
            lat: 26.53619957,
            lon: -81.75520325
        },
        SAN: {
            name: 'San Diego International Airport',
            city: 'San Diego',
            state: 'CA',
            country: 'United States',
            carriers: 57,
            flights: 51,
            tz: 'America/Los_Angeles',
            lat: 32.73360062,
            lon: -117.1900024
        },
        SAV: {
            name: 'Savannah Hilton Head International Airport',
            city: 'Savannah',
            state: 'GA',
            country: 'United States',
            carriers: 21,
            flights: 18,
            tz: 'America/New_York',
            lat: 32.12760162,
            lon: -81.20210266
        },
        SBA: {
            name: 'Santa Barbara Municipal Airport',
            city: 'Santa Barbara',
            state: 'CA',
            country: 'United States',
            carriers: 17,
            flights: 12,
            tz: 'America/Los_Angeles',
            lat: 34.42620087,
            lon: -119.8399963
        },
        SJT: {
            name: 'San Angelo Regional Mathis Field',
            city: 'San Angelo',
            state: 'TX',
            country: 'United States',
            carriers: 4,
            flights: 3,
            tz: 'America/Chicago',
            lat: 31.35770035,
            lon: -100.4960022
        },
        SJU: {
            name: 'Luis Munoz Marin International Airport',
            city: 'San Juan',
            state: 'PR',
            country: 'Puerto Rico',
            carriers: 37,
            flights: 60,
            tz: 'America/Puerto_Rico',
            lat: 18.43939972,
            lon: -66.00180054
        },
        SMX: {
            name: 'Santa Maria Pub/Capt G Allan Hancock Field',
            city: 'Santa Maria',
            state: 'CA',
            country: 'United States',
            carriers: 3,
            flights: 2,
            tz: 'America/Los_Angeles',
            lat: 34.89889908,
            lon: -120.4570007
        },
        SPI: {
            name: 'Abraham Lincoln Capital Airport',
            city: 'Springfield',
            state: 'IL',
            country: 'United States',
            carriers: 4,
            flights: 3,
            tz: 'America/Chicago',
            lat: 39.84410095,
            lon: -89.67790222
        },
        STT: {
            name: 'Cyril E. King Airport',
            city: 'St. Thomas',
            state: 'VI',
            country: 'Virgin Islands',
            carriers: 12,
            flights: 17,
            tz: 'America/St_Thomas',
            lat: 18.33729935,
            lon: -64.9733963
        },
        SYR: {
            name: 'Syracuse Hancock International Airport',
            city: 'Syracuse',
            state: 'NY',
            country: 'United States',
            carriers: 26,
            flights: 21,
            tz: 'America/New_York',
            lat: 43.11119843,
            lon: -76.10630035
        },
        TPA: {
            name: 'Tampa International Airport',
            city: 'Tampa',
            state: 'FL',
            country: 'United States',
            carriers: 48,
            flights: 74,
            tz: 'America/New_York',
            lat: 27.97550011,
            lon: -82.53320313
        },
        TXK: {
            name: 'Texarkana Regional Webb Field',
            city: 'Texarkana',
            state: 'AR',
            country: 'United States',
            carriers: 2,
            flights: 2,
            tz: 'America/Chicago',
            lat: 33.45370102,
            lon: -93.99099731
        },
        TYR: {
            name: 'Tyler Pounds Regional Airport',
            city: 'Tyler',
            state: 'TX',
            country: 'United States',
            carriers: 3,
            flights: 2,
            tz: 'America/Chicago',
            lat: 32.35409927,
            lon: -95.40239716
        },
        ABI: {
            name: 'Abilene Regional Airport',
            city: 'Abilene',
            state: 'TX',
            country: 'United States',
            carriers: 4,
            flights: 2,
            tz: 'America/Chicago',
            lat: 32.41130066,
            lon: -99.68190002
        },
        ABY: {
            name: 'Southwest Georgia Regional Airport',
            city: 'Albany',
            state: 'GA',
            country: 'United States',
            carriers: 2,
            flights: 1,
            tz: 'America/New_York',
            lat: 31.53549957,
            lon: -84.19450378
        },
        ADK: {
            name: 'Adak Airport',
            city: 'Adak Island',
            state: 'AK',
            country: 'United States',
            carriers: 1,
            flights: 1,
            tz: 'America/Adak',
            lat: 51.87799835,
            lon: -176.6459961
        },
        ADQ: {
            name: 'Kodiak Airport',
            city: 'Kodiak',
            state: 'AK',
            country: 'United States',
            carriers: 7,
            flights: 12,
            tz: 'America/Anchorage',
            lat: 57.75,
            lon: -152.4940033
        },
        AEX: {
            name: 'Alexandria International Airport',
            city: 'Alexandria',
            state: 'LA',
            country: 'United States',
            carriers: 7,
            flights: 5,
            tz: 'America/Chicago',
            lat: 31.32740021,
            lon: -92.54979706
        },
        AMA: {
            name: 'Rick Husband Amarillo International Airport',
            city: 'Amarillo',
            state: 'TX',
            country: 'United States',
            carriers: 10,
            flights: 7,
            tz: 'America/Chicago',
            lat: 35.2193985,
            lon: -101.7060013
        },
        ANC: {
            name: 'Ted Stevens Anchorage International Airport',
            city: 'Anchorage',
            state: 'AK',
            country: 'United States',
            carriers: 47,
            flights: 62,
            tz: 'America/Anchorage',
            lat: 61.17440033,
            lon: -149.9960022
        },
        APN: {
            name: 'Alpena County Regional Airport',
            city: 'Alpena',
            state: 'MI',
            country: 'United States',
            carriers: 4,
            flights: 2,
            tz: 'America/New_York',
            lat: 45.0780983,
            lon: -83.56030273
        },
        ASE: {
            name: 'Aspen-Pitkin Co/Sardy Field',
            city: 'Aspen',
            state: 'CO',
            country: 'United States',
            carriers: 5,
            flights: 5,
            tz: 'America/Denver',
            lat: 39.22320175,
            lon: -106.8690033
        },
        AVL: {
            name: 'Asheville Regional Airport',
            city: 'Asheville',
            state: 'NC',
            country: 'United States',
            carriers: 10,
            flights: 7,
            tz: 'America/New_York',
            lat: 35.43619919,
            lon: -82.54180145
        },
        BGM: {
            name: 'Greater Binghamton/Edwin A Link field',
            city: 'Binghamton',
            state: 'NY',
            country: 'United States',
            carriers: 8,
            flights: 3,
            tz: 'America/New_York',
            lat: 42.20869827,
            lon: -75.97979736
        },
        BLI: {
            name: 'Bellingham International Airport',
            city: 'Bellingham',
            state: 'WA',
            country: 'United States',
            carriers: 8,
            flights: 8,
            tz: 'America/Los_Angeles',
            lat: 48.7928009,
            lon: -122.538002
        },
        BMI: {
            name: 'Central Illinois Regional Airport at Bloomington-Normal',
            city: 'Bloomington',
            state: 'IL',
            country: 'United States',
            carriers: 12,
            flights: 7,
            tz: 'America/Chicago',
            lat: 40.47710037,
            lon: -88.91590118
        },
        BNA: {
            name: 'Nashville International Airport',
            city: 'Nashville',
            state: 'TN',
            country: 'United States',
            carriers: 38,
            flights: 53,
            tz: 'America/Chicago',
            lat: 36.12450027,
            lon: -86.67819977
        },
        BOS: {
            name: 'General Edward Lawrence Logan International Airport',
            city: 'Boston',
            state: 'MA',
            country: 'United States',
            carriers: 68,
            flights: 113,
            tz: 'America/New_York',
            lat: 42.36429977,
            lon: -71.00520325
        },
        BRW: {
            name: 'Wiley Post Will Rogers Memorial Airport',
            city: 'Barrow',
            state: 'AK',
            country: 'United States',
            carriers: 5,
            flights: 7,
            tz: 'America/Anchorage',
            lat: 71.285402,
            lon: -156.766008
        },
        CLE: {
            name: 'Cleveland Hopkins International Airport',
            city: 'Cleveland',
            state: 'OH',
            country: 'United States',
            carriers: 44,
            flights: 102,
            tz: 'America/New_York',
            lat: 41.4117012,
            lon: -81.84980011
        },
        CLT: {
            name: 'Charlotte Douglas International Airport',
            city: 'Charlotte',
            state: 'NC',
            country: 'United States',
            carriers: 39,
            flights: 133,
            tz: 'America/New_York',
            lat: 35.2140007,
            lon: -80.94309998
        },
        CMX: {
            name: 'Houghton County Memorial Airport',
            city: 'Hancock',
            state: 'MI',
            country: 'United States',
            carriers: 4,
            flights: 1,
            tz: 'America/New_York',
            lat: 47.16839981,
            lon: -88.4890976
        },
        CRP: {
            name: 'Corpus Christi International Airport',
            city: 'Corpus Christi',
            state: 'TX',
            country: 'United States',
            carriers: 12,
            flights: 5,
            tz: 'America/Chicago',
            lat: 27.77039909,
            lon: -97.50119781
        },
        CRW: {
            name: 'Yeager Airport',
            city: 'Charleston',
            state: 'WV',
            country: 'United States',
            carriers: 9,
            flights: 10,
            tz: 'America/New_York',
            lat: 38.37310028,
            lon: -81.59320068
        },
        CSG: {
            name: 'Columbus Metropolitan Airport',
            city: 'Columbus',
            state: 'GA',
            country: 'United States',
            carriers: 2,
            flights: 1,
            tz: 'America/New_York',
            lat: 32.5163002,
            lon: -84.93890381
        },
        CVG: {
            name: 'Cincinnati Northern Kentucky International Airport',
            city: 'Cincinnati',
            state: 'OH',
            country: 'United States',
            carriers: 39,
            flights: 115,
            tz: 'America/New_York',
            lat: 39.04880142,
            lon: -84.6678009
        },
        DAY: {
            name: 'James M Cox Dayton International Airport',
            city: 'Dayton',
            state: 'OH',
            country: 'United States',
            carriers: 29,
            flights: 27,
            tz: 'America/New_York',
            lat: 39.90240097,
            lon: -84.2193985
        },
        DTW: {
            name: 'Detroit Metropolitan Wayne County Airport',
            city: 'Detroit',
            state: 'MI',
            country: 'United States',
            carriers: 45,
            flights: 161,
            tz: 'America/New_York',
            lat: 42.21239853,
            lon: -83.35340118
        },
        ELM: {
            name: 'Elmira Corning Regional Airport',
            city: 'Elmira',
            state: 'NY',
            country: 'United States',
            carriers: 7,
            flights: 3,
            tz: 'America/New_York',
            lat: 42.15990067,
            lon: -76.89160156
        },
        ELP: {
            name: 'El Paso International Airport',
            city: 'El Paso',
            state: 'TX',
            country: 'United States',
            carriers: 23,
            flights: 20,
            tz: 'America/Denver',
            lat: 31.80719948,
            lon: -106.3779984
        },
        EVV: {
            name: 'Evansville Regional Airport',
            city: 'Evansville',
            state: 'IN',
            country: 'United States',
            carriers: 10,
            flights: 7,
            tz: 'America/Chicago',
            lat: 38.03699875,
            lon: -87.53240204
        },
        FAI: {
            name: 'Fairbanks International Airport',
            city: 'Fairbanks',
            state: 'AK',
            country: 'United States',
            carriers: 18,
            flights: 32,
            tz: 'America/Anchorage',
            lat: 64.81510162,
            lon: -147.8560028
        },
        FCA: {
            name: 'Glacier Park International Airport',
            city: 'Kalispell',
            state: 'MT',
            country: 'United States',
            carriers: 10,
            flights: 8,
            tz: 'America/Denver',
            lat: 48.3105011,
            lon: -114.2559967
        },
        GTF: {
            name: 'Great Falls International Airport',
            city: 'Great Falls',
            state: 'MT',
            country: 'United States',
            carriers: 10,
            flights: 10,
            tz: 'America/Denver',
            lat: 47.48199844,
            lon: -111.3710022
        },
        GTR: {
            name: 'Golden Triangle Regional Airport',
            city: 'Columbus Mississippi',
            state: 'MS',
            country: 'United States',
            carriers: 2,
            flights: 1,
            tz: 'America/Chicago',
            lat: 33.45029831,
            lon: -88.59140015
        },
        HPN: {
            name: 'Westchester County Airport',
            city: 'White Plains',
            state: 'NY',
            country: 'United States',
            carriers: 13,
            flights: 16,
            tz: 'America/New_York',
            lat: 41.06700134,
            lon: -73.70760345
        },
        IMT: {
            name: 'Ford Airport',
            city: 'Iron Mountain',
            state: 'MI',
            country: 'United States',
            carriers: 2,
            flights: 2,
            tz: 'America/Chicago',
            lat: 45.81840134,
            lon: -88.11450195
        },
        JAC: {
            name: 'Jackson Hole Airport',
            city: 'Jacksn Hole',
            state: 'WY',
            country: 'United States',
            carriers: 9,
            flights: 7,
            tz: 'America/Denver',
            lat: 43.6072998,
            lon: -110.737999
        },
        JMS: {
            name: 'Jamestown Regional Airport',
            city: 'Jamestown',
            state: 'ND',
            country: 'United States',
            carriers: 3,
            flights: 3,
            tz: 'America/Chicago',
            lat: 46.92969894,
            lon: -98.67819977
        },
        JNU: {
            name: 'Juneau International Airport',
            city: 'Juneau',
            state: 'AK',
            country: 'United States',
            carriers: 11,
            flights: 15,
            tz: 'America/Anchorage',
            lat: 58.35499954,
            lon: -134.576004
        },
        LBE: {
            name: 'Arnold Palmer Regional Airport',
            city: 'Latrobe',
            state: 'PA',
            country: 'United States',
            carriers: 3,
            flights: 1,
            tz: 'America/New_York',
            lat: 40.27590179,
            lon: -79.40480042
        },
        LGA: {
            name: 'La Guardia Airport',
            city: 'New York',
            state: 'NY',
            country: 'United States',
            carriers: 30,
            flights: 82,
            tz: 'America/New_York',
            lat: 40.77719879,
            lon: -73.87259674
        },
        LWS: {
            name: 'Lewiston Nez Perce County Airport',
            city: 'Lewiston',
            state: 'ID',
            country: 'United States',
            carriers: 5,
            flights: 4,
            tz: 'America/Los_Angeles',
            lat: 46.37450027,
            lon: -117.0149994
        },
        MAF: {
            name: 'Midland International Airport',
            city: 'Midland',
            state: 'TX',
            country: 'United States',
            carriers: 11,
            flights: 8,
            tz: 'America/Chicago',
            lat: 31.94249916,
            lon: -102.2020035
        },
        MBS: {
            name: 'MBS International Airport',
            city: 'Saginaw',
            state: 'MI',
            country: 'United States',
            carriers: 7,
            flights: 3,
            tz: 'America/New_York',
            lat: 43.53290176,
            lon: -84.07959747
        },
        MEI: {
            name: 'Key Field',
            city: 'Meridian',
            state: 'MS',
            country: 'United States',
            carriers: 3,
            flights: 1,
            tz: 'America/Chicago',
            lat: 32.33259964,
            lon: -88.75189972
        },
        MFE: {
            name: 'Mc Allen Miller International Airport',
            city: 'Mcallen',
            state: 'TX',
            country: 'United States',
            carriers: 11,
            flights: 4,
            tz: 'America/Chicago',
            lat: 26.17580032,
            lon: -98.23860168
        },
        MKE: {
            name: 'General Mitchell International Airport',
            city: 'Milwaukee',
            state: 'WI',
            country: 'United States',
            carriers: 30,
            flights: 59,
            tz: 'America/Chicago',
            lat: 42.94720078,
            lon: -87.89659882
        },
        MKG: {
            name: 'Muskegon County Airport',
            city: 'Muskegon',
            state: 'MI',
            country: 'United States',
            carriers: 5,
            flights: 3,
            tz: 'America/New_York',
            lat: 43.16949844,
            lon: -86.23819733
        },
        MLB: {
            name: 'Melbourne International Airport',
            city: 'Melbourne',
            state: 'FL',
            country: 'United States',
            carriers: 5,
            flights: 1,
            tz: 'America/New_York',
            lat: 28.10280037,
            lon: -80.64530182
        },
        MLU: {
            name: 'Monroe Regional Airport',
            city: 'Monroe',
            state: 'LA',
            country: 'United States',
            carriers: 6,
            flights: 4,
            tz: 'America/Chicago',
            lat: 32.51089859,
            lon: -92.03769684
        },
        MYR: {
            name: 'Myrtle Beach International Airport',
            city: 'Myrtle Beach',
            state: 'SC',
            country: 'United States',
            carriers: 12,
            flights: 13,
            tz: 'America/New_York',
            lat: 33.67969894,
            lon: -78.92829895
        },
        OAK: {
            name: 'Metropolitan Oakland International Airport',
            city: 'Oakland',
            state: 'CA',
            country: 'United States',
            carriers: 19,
            flights: 35,
            tz: 'America/Los_Angeles',
            lat: 37.72129822,
            lon: -122.2210007
        },
        PBI: {
            name: 'Palm Beach International Airport',
            city: 'West Palm Beach',
            state: 'FL',
            country: 'United States',
            carriers: 24,
            flights: 31,
            tz: 'America/New_York',
            lat: 26.68320084,
            lon: -80.09559631
        },
        PNS: {
            name: 'Pensacola Regional Airport',
            city: 'Pensacola',
            state: 'FL',
            country: 'United States',
            carriers: 15,
            flights: 11,
            tz: 'America/Chicago',
            lat: 30.47340012,
            lon: -87.18659973
        },
        PSC: {
            name: 'Tri Cities Airport',
            city: 'Pasco',
            state: 'WA',
            country: 'United States',
            carriers: 12,
            flights: 7,
            tz: 'America/Los_Angeles',
            lat: 46.26470184,
            lon: -119.1190033
        },
        PSP: {
            name: 'Palm Springs International Airport',
            city: 'Palm Springs',
            state: 'CA',
            country: 'United States',
            carriers: 16,
            flights: 17,
            tz: 'America/Los_Angeles',
            lat: 33.82970047,
            lon: -116.5070038
        },
        RAP: {
            name: 'Rapid City Regional Airport',
            city: 'Rapid City',
            state: 'SD',
            country: 'United States',
            carriers: 11,
            flights: 9,
            tz: 'America/Denver',
            lat: 44.04529953,
            lon: -103.0569992
        },
        RDU: {
            name: 'Raleigh Durham International Airport',
            city: 'Raleigh-durham',
            state: 'NC',
            country: 'United States',
            carriers: 44,
            flights: 47,
            tz: 'America/New_York',
            lat: 35.87760162,
            lon: -78.78749847
        },
        RHI: {
            name: 'Rhinelander Oneida County Airport',
            city: 'Rhinelander',
            state: 'WI',
            country: 'United States',
            carriers: 6,
            flights: 4,
            tz: 'America/Chicago',
            lat: 45.63119888,
            lon: -89.46749878
        },
        RNO: {
            name: 'Reno Tahoe International Airport',
            city: 'Reno',
            state: 'NV',
            country: 'United States',
            carriers: 22,
            flights: 21,
            tz: 'America/Los_Angeles',
            lat: 39.49909973,
            lon: -119.7679977
        },
        ROC: {
            name: 'Greater Rochester International Airport',
            city: 'Rochester',
            state: 'NY',
            country: 'United States',
            carriers: 31,
            flights: 22,
            tz: 'America/New_York',
            lat: 43.1189003,
            lon: -77.67240143
        },
        SBN: {
            name: 'South Bend Regional Airport',
            city: 'South Bend',
            state: 'IN',
            country: 'United States',
            carriers: 14,
            flights: 16,
            tz: 'America/New_York',
            lat: 41.70869827,
            lon: -86.31729889
        },
        SCE: {
            name: 'University Park Airport',
            city: 'State College Pennsylvania',
            state: 'PA',
            country: 'United States',
            carriers: 8,
            flights: 4,
            tz: 'America/New_York',
            lat: 40.84930038,
            lon: -77.84870148
        },
        SDF: {
            name: 'Louisville International Standiford Field',
            city: 'Louisville',
            state: 'KY',
            country: 'United States',
            carriers: 26,
            flights: 32,
            tz: 'America/New_York',
            lat: 38.1744,
            lon: -85.736
        },
        SFO: {
            name: 'San Francisco International Airport',
            city: 'San Francisco',
            state: 'CA',
            country: 'United States',
            carriers: 76,
            flights: 147,
            tz: 'America/Los_Angeles',
            lat: 37.61899948,
            lon: -122.375
        },
        SGF: {
            name: 'Springfield Branson National Airport',
            city: 'Springfield',
            state: 'MO',
            country: 'United States',
            carriers: 16,
            flights: 15,
            tz: 'America/Chicago',
            lat: 37.24570084,
            lon: -93.38860321
        },
        SHV: {
            name: 'Shreveport Regional Airport',
            city: 'Shreveport',
            state: 'LA',
            country: 'United States',
            carriers: 13,
            flights: 10,
            tz: 'America/Chicago',
            lat: 32.44660187,
            lon: -93.82559967
        },
        SPS: {
            name: 'Sheppard Air Force Base-Wichita Falls Municipal Airport',
            city: 'Wichita Falls',
            state: 'TX',
            country: 'United States',
            carriers: 3,
            flights: 2,
            tz: 'America/Chicago',
            lat: 33.98880005,
            lon: -98.49189758
        },
        STX: {
            name: 'Henry E Rohlsen Airport',
            city: 'St. Croix Island',
            state: 'VI',
            country: 'Virgin Islands',
            carriers: 10,
            flights: 9,
            tz: 'America/St_Thomas',
            lat: 17.70190048,
            lon: -64.79859924
        },
        SUN: {
            name: 'Friedman Memorial Airport',
            city: 'Hailey',
            state: 'ID',
            country: 'United States',
            carriers: 4,
            flights: 4,
            tz: 'America/Denver',
            lat: 43.50439835,
            lon: -114.2959976
        },
        TUS: {
            name: 'Tucson International Airport',
            city: 'Tucson',
            state: 'AZ',
            country: 'United States',
            carriers: 26,
            flights: 25,
            tz: 'America/Phoenix',
            lat: 32.11610031,
            lon: -110.9410019
        },
        WRG: {
            name: 'Wrangell Airport',
            city: 'Wrangell',
            state: 'AK',
            country: 'United States',
            carriers: 3,
            flights: 2,
            tz: 'America/Anchorage',
            lat: 56.48429871,
            lon: -132.3699951
        },
        XNA: {
            name: 'Northwest Arkansas Regional Airport',
            city: 'Bentonville',
            state: 'AR',
            country: 'United States',
            carriers: 13,
            flights: 15,
            tz: 'America/Chicago',
            lat: 36.281898,
            lon: -94.306801
        },
        ABE: {
            name: 'Lehigh Valley International Airport',
            city: 'Allentown',
            state: 'PA',
            country: 'United States',
            carriers: 11,
            flights: 14,
            tz: 'America/New_York',
            lat: 40.65209961,
            lon: -75.44080353
        },
        ABQ: {
            name: 'Albuquerque International Sunport Airport',
            city: 'Albuquerque',
            state: 'NM',
            country: 'United States',
            carriers: 25,
            flights: 41,
            tz: 'America/Denver',
            lat: 35.04019928,
            lon: -106.6090012
        },
        ABR: {
            name: 'Aberdeen Regional Airport',
            city: 'Aberdeen',
            state: 'SD',
            country: 'United States',
            carriers: 5,
            flights: 3,
            tz: 'America/Chicago',
            lat: 45.44910049,
            lon: -98.42179871
        },
        AGS: {
            name: 'Augusta Regional At Bush Field',
            city: 'Bush Field',
            state: 'GA',
            country: 'United States',
            carriers: 8,
            flights: 2,
            tz: 'America/New_York',
            lat: 33.36989975,
            lon: -81.96450043
        },
        ATW: {
            name: 'Appleton International Airport',
            city: 'Appleton',
            state: 'WI',
            country: 'United States',
            carriers: 11,
            flights: 8,
            tz: 'America/Chicago',
            lat: 44.2580986,
            lon: -88.51909637
        },
        AVP: {
            name: 'Wilkes Barre Scranton International Airport',
            city: 'Scranton',
            state: 'PA',
            country: 'United States',
            carriers: 8,
            flights: 8,
            tz: 'America/New_York',
            lat: 41.33850098,
            lon: -75.7233963
        },
        BJI: {
            name: 'Bemidji Regional Airport',
            city: 'Bemidji',
            state: 'MN',
            country: 'United States',
            carriers: 4,
            flights: 1,
            tz: 'America/Chicago',
            lat: 47.50939941,
            lon: -94.93370056
        },
        BOI: {
            name: 'Boise Air Terminal/Gowen field',
            city: 'Boise',
            state: 'ID',
            country: 'United States',
            carriers: 21,
            flights: 22,
            tz: 'America/Denver',
            lat: 43.56439972,
            lon: -116.2229996
        },
        BPT: {
            name: 'Southeast Texas Regional Airport',
            city: 'Beaumont',
            state: 'TX',
            country: 'United States',
            carriers: 4,
            flights: 1,
            tz: 'America/Chicago',
            lat: 29.95079994,
            lon: -94.02069855
        },
        BRO: {
            name: 'Brownsville South Padre Island International Airport',
            city: 'Brownsville',
            state: 'TX',
            country: 'United States',
            carriers: 9,
            flights: 5,
            tz: 'America/Chicago',
            lat: 25.90679932,
            lon: -97.42590332
        },
        BTV: {
            name: 'Burlington International Airport',
            city: 'Burlington',
            state: 'VT',
            country: 'United States',
            carriers: 16,
            flights: 15,
            tz: 'America/New_York',
            lat: 44.47190094,
            lon: -73.15329742
        },
        BZN: {
            name: 'Gallatin Field',
            city: 'Bozeman',
            state: 'MT',
            country: 'United States',
            carriers: 8,
            flights: 10,
            tz: 'America/Denver',
            lat: 45.77750015,
            lon: -111.1529999
        },
        CHO: {
            name: 'Charlottesville Albemarle Airport',
            city: 'Charlottesville VA',
            state: 'VA',
            country: 'United States',
            carriers: 9,
            flights: 7,
            tz: 'America/New_York',
            lat: 38.1385994,
            lon: -78.45290375
        },
        CID: {
            name: 'The Eastern Iowa Airport',
            city: 'Cedar Rapids',
            state: 'IA',
            country: 'United States',
            carriers: 20,
            flights: 15,
            tz: 'America/Chicago',
            lat: 41.88470078,
            lon: -91.71080017
        },
        COD: {
            name: 'Yellowstone Regional Airport',
            city: 'Cody',
            state: 'WY',
            country: 'United States',
            carriers: 3,
            flights: 2,
            tz: 'America/Denver',
            lat: 44.52019882,
            lon: -109.0240021
        },
        DHN: {
            name: 'Dothan Regional Airport',
            city: 'Dothan',
            state: 'AL',
            country: 'United States',
            carriers: 4,
            flights: 1,
            tz: 'America/Chicago',
            lat: 31.32130051,
            lon: -85.44960022
        },
        DVL: {
            name: 'Devils Lake Regional Airport',
            city: 'Devils Lake',
            state: 'ND',
            country: 'United States',
            carriers: 2,
            flights: 2,
            tz: 'America/Chicago',
            lat: 48.11420059,
            lon: -98.90879822
        },
        EKO: {
            name: 'Elko Regional Airport',
            city: 'Elko',
            state: 'NV',
            country: 'United States',
            carriers: 1,
            flights: 1,
            tz: 'America/Los_Angeles',
            lat: 40.82490158,
            lon: -115.7919998
        },
        ERI: {
            name: 'Erie International Tom Ridge Field',
            city: 'Erie',
            state: 'PA',
            country: 'United States',
            carriers: 7,
            flights: 3,
            tz: 'America/New_York',
            lat: 42.08312701,
            lon: -80.17386675
        },
        EWR: {
            name: 'Newark Liberty International Airport',
            city: 'Newark',
            state: 'NJ',
            country: 'United States',
            carriers: 64,
            flights: 220,
            tz: 'America/New_York',
            lat: 40.69250107,
            lon: -74.16870117
        },
        FAT: {
            name: 'Fresno Yosemite International Airport',
            city: 'Fresno',
            state: 'CA',
            country: 'United States',
            carriers: 19,
            flights: 14,
            tz: 'America/Los_Angeles',
            lat: 36.77619934,
            lon: -119.7180023
        },
        FLG: {
            name: 'Flagstaff Pulliam Airport',
            city: 'Flagstaff',
            state: 'AZ',
            country: 'United States',
            carriers: 6,
            flights: 3,
            tz: 'America/Phoenix',
            lat: 35.13850021,
            lon: -111.6709976
        },
        FLL: {
            name: 'Fort Lauderdale Hollywood International Airport',
            city: 'Fort Lauderdale',
            state: 'FL',
            country: 'United States',
            carriers: 46,
            flights: 108,
            tz: 'America/New_York',
            lat: 26.07259941,
            lon: -80.15270233
        },
        FNT: {
            name: 'Bishop International Airport',
            city: 'Flint',
            state: 'MI',
            country: 'United States',
            carriers: 10,
            flights: 15,
            tz: 'America/New_York',
            lat: 42.9654007,
            lon: -83.74359894
        },
        FSD: {
            name: 'Joe Foss Field Airport',
            city: 'Sioux Falls',
            state: 'SD',
            country: 'United States',
            carriers: 11,
            flights: 9,
            tz: 'America/Chicago',
            lat: 43.58200073,
            lon: -96.74189758
        },
        GGG: {
            name: 'East Texas Regional Airport',
            city: 'Longview',
            state: 'TX',
            country: 'United States',
            carriers: 1,
            flights: 1,
            tz: 'America/Chicago',
            lat: 32.38399887,
            lon: -94.71150208
        },
        GRB: {
            name: 'Austin Straubel International Airport',
            city: 'Green Bay',
            state: 'WI',
            country: 'United States',
            carriers: 16,
            flights: 12,
            tz: 'America/Chicago',
            lat: 44.48509979,
            lon: -88.12960052
        },
        GRK: {
            name: 'Robert Gray  Army Air Field Airport',
            city: 'Killeen',
            state: 'TX',
            country: 'United States',
            carriers: 4,
            flights: 3,
            tz: 'America/Chicago',
            lat: 31.06719971,
            lon: -97.8289032
        },
        GRR: {
            name: 'Gerald R. Ford International Airport',
            city: 'Grand Rapids',
            state: 'MI',
            country: 'United States',
            carriers: 26,
            flights: 21,
            tz: 'America/New_York',
            lat: 42.88079834,
            lon: -85.52279663
        },
        GSO: {
            name: 'Piedmont Triad International Airport',
            city: 'Greensboro',
            state: 'NC',
            country: 'United States',
            carriers: 26,
            flights: 24,
            tz: 'America/New_York',
            lat: 36.09780121,
            lon: -79.93730164
        },
        HRL: {
            name: 'Valley International Airport',
            city: 'Harlingen',
            state: 'TX',
            country: 'United States',
            carriers: 10,
            flights: 9,
            tz: 'America/Chicago',
            lat: 26.22850037,
            lon: -97.65440369
        },
        IAG: {
            name: 'Niagara Falls International Airport',
            city: 'Niagara Falls',
            state: 'NY',
            country: 'United States',
            carriers: 1,
            flights: 4,
            tz: 'America/New_York',
            lat: 43.1072998,
            lon: -78.94619751
        },
        ICT: {
            name: 'Wichita Mid Continent Airport',
            city: 'Wichita',
            state: 'KS',
            country: 'United States',
            carriers: 22,
            flights: 14,
            tz: 'America/Chicago',
            lat: 37.64989853,
            lon: -97.43309784
        },
        ISN: {
            name: 'Sloulin Field International Airport',
            city: 'Williston',
            state: 'ND',
            country: 'United States',
            carriers: 3,
            flights: 2,
            tz: 'America/Chicago',
            lat: 48.17789841,
            lon: -103.6419983
        },
        JAN: {
            name: 'Jackson-Medgar Wiley Evers International Airport',
            city: 'Jackson',
            state: 'MS',
            country: 'United States',
            carriers: 15,
            flights: 16,
            tz: 'America/Chicago',
            lat: 32.31119919,
            lon: -90.07589722
        },
        JFK: {
            name: 'John F Kennedy International Airport',
            city: 'New York',
            state: 'NY',
            country: 'United States',
            carriers: 100,
            flights: 233,
            tz: 'America/New_York',
            lat: 40.63980103,
            lon: -73.77890015
        },
        LBB: {
            name: 'Lubbock Preston Smith International Airport',
            city: 'Lubbock',
            state: 'TX',
            country: 'United States',
            carriers: 11,
            flights: 10,
            tz: 'America/Chicago',
            lat: 33.66360092,
            lon: -101.822998
        },
        LIH: {
            name: 'Lihue Airport',
            city: 'Lihue',
            state: 'HI',
            country: 'United States',
            carriers: 13,
            flights: 7,
            tz: 'Pacific/Honolulu',
            lat: 21.97599983,
            lon: -159.3390045
        },
        MFR: {
            name: 'Rogue Valley International Medford Airport',
            city: 'Medford',
            state: 'OR',
            country: 'United States',
            carriers: 13,
            flights: 10,
            tz: 'America/Los_Angeles',
            lat: 42.37419891,
            lon: -122.8730011
        },
        MGM: {
            name: 'Montgomery Regional (Dannelly Field) Airport',
            city: 'MONTGOMERY',
            state: 'AL',
            country: 'United States',
            carriers: 9,
            flights: 4,
            tz: 'America/Chicago',
            lat: 32.30059814,
            lon: -86.39399719
        },
        MHT: {
            name: 'Manchester Airport',
            city: 'Manchester NH',
            state: 'NH',
            country: 'United States',
            carriers: 16,
            flights: 20,
            tz: 'America/New_York',
            lat: 42.93259811,
            lon: -71.43569946
        },
        MLI: {
            name: 'Quad City International Airport',
            city: 'Moline',
            state: 'IL',
            country: 'United States',
            carriers: 14,
            flights: 11,
            tz: 'America/Chicago',
            lat: 41.44850159,
            lon: -90.50749969
        },
        MMH: {
            name: 'Mammoth Yosemite Airport',
            city: 'Mammoth Lakes',
            state: 'CA',
            country: 'United States',
            carriers: 2,
            flights: 1,
            tz: 'America/Los_Angeles',
            lat: 37.62409973,
            lon: -118.8379974
        },
        MOT: {
            name: 'Minot International Airport',
            city: 'Minot',
            state: 'ND',
            country: 'United States',
            carriers: 4,
            flights: 1,
            tz: 'America/Chicago',
            lat: 48.25939941,
            lon: -101.2799988
        },
        MSN: {
            name: 'Dane County Regional Truax Field',
            city: 'Madison',
            state: 'WI',
            country: 'United States',
            carriers: 20,
            flights: 18,
            tz: 'America/Chicago',
            lat: 43.13990021,
            lon: -89.33750153
        },
        MVY: {
            name: 'Martha\'s Vineyard Airport',
            city: 'Vineyard Haven MA',
            state: 'MA',
            country: 'United States',
            carriers: 2,
            flights: 7,
            tz: 'America/New_York',
            lat: 41.39310074,
            lon: -70.61430359
        },
        PHL: {
            name: 'Philadelphia International Airport',
            city: 'Philadelphia',
            state: 'PA',
            country: 'United States',
            carriers: 51,
            flights: 133,
            tz: 'America/New_York',
            lat: 39.87189865,
            lon: -75.2410965
        },
        PWM: {
            name: 'Portland International Jetport Airport',
            city: 'Portland',
            state: 'ME',
            country: 'United States',
            carriers: 18,
            flights: 17,
            tz: 'America/New_York',
            lat: 43.64619827,
            lon: -70.30930328
        },
        ROW: {
            name: 'Roswell International Air Center Airport',
            city: 'Roswell',
            state: 'NM',
            country: 'United States',
            carriers: 1,
            flights: 1,
            tz: 'America/Denver',
            lat: 33.30160141,
            lon: -104.5309982
        },
        SBP: {
            name: 'San Luis County Regional Airport',
            city: 'San Luis Obispo',
            state: 'CA',
            country: 'United States',
            carriers: 8,
            flights: 3,
            tz: 'America/Los_Angeles',
            lat: 35.23680115,
            lon: -120.6419983
        },
        SCC: {
            name: 'Deadhorse Airport',
            city: 'Deadhorse',
            state: 'AK',
            country: 'United States',
            carriers: 5,
            flights: 4,
            tz: 'America/Anchorage',
            lat: 70.19470215,
            lon: -148.4649963
        },
        SGU: {
            name: 'St George Municipal Airport',
            city: 'Saint George',
            state: 'UT',
            country: 'United States',
            carriers: 2,
            flights: 2,
            tz: 'America/Denver',
            lat: 37.03638889,
            lon: -113.5103056
        },
        SIT: {
            name: 'Sitka Rocky Gutierrez Airport',
            city: 'Sitka',
            state: 'AK',
            country: 'United States',
            carriers: 7,
            flights: 3,
            tz: 'America/Anchorage',
            lat: 57.04710007,
            lon: -135.3619995
        },
        SRQ: {
            name: 'Sarasota Bradenton International Airport',
            city: 'Sarasota',
            state: 'FL',
            country: 'United States',
            carriers: 14,
            flights: 14,
            tz: 'America/New_York',
            lat: 27.39539909,
            lon: -82.55439758
        },
        STL: {
            name: 'Lambert St Louis International Airport',
            city: 'St. Louis',
            state: 'MO',
            country: 'United States',
            carriers: 46,
            flights: 78,
            tz: 'America/Chicago',
            lat: 38.74869919,
            lon: -90.37000275
        },
        STS: {
            name: 'Charles M. Schulz Sonoma County Airport',
            city: 'Santa Rosa',
            state: 'CA',
            country: 'United States',
            carriers: 5,
            flights: 4,
            tz: 'America/Los_Angeles',
            lat: 38.50899887,
            lon: -122.8130035
        },
        SWF: {
            name: 'Stewart International Airport',
            city: 'Newburgh',
            state: 'NY',
            country: 'United States',
            carriers: 8,
            flights: 9,
            tz: 'America/New_York',
            lat: 41.5041008,
            lon: -74.10479736
        },
        TUL: {
            name: 'Tulsa International Airport',
            city: 'Tulsa',
            state: 'OK',
            country: 'United States',
            carriers: 21,
            flights: 26,
            tz: 'America/Chicago',
            lat: 36.19839859,
            lon: -95.88809967
        },
        TVC: {
            name: 'Cherry Capital Airport',
            city: 'Traverse City',
            state: 'MI',
            country: 'United States',
            carriers: 9,
            flights: 6,
            tz: 'America/New_York',
            lat: 44.74140167,
            lon: -85.5821991
        },
        TWF: {
            name: 'Joslin Field Magic Valley Regional Airport',
            city: 'Twin Falls',
            state: 'ID',
            country: 'United States',
            carriers: 1,
            flights: 1,
            tz: 'America/Denver',
            lat: 42.48180008,
            lon: -114.487999
        },
        VLD: {
            name: 'Valdosta Regional Airport',
            city: 'Valdosta',
            state: 'GA',
            country: 'United States',
            carriers: 2,
            flights: 1,
            tz: 'America/New_York',
            lat: 30.78249931,
            lon: -83.27670288
        },
        ACT: {
            name: 'Waco Regional Airport',
            city: 'Waco',
            state: 'TX',
            country: 'United States',
            carriers: 2,
            flights: 2,
            tz: 'America/Chicago',
            lat: 31.61129951,
            lon: -97.23049927
        },
        ACY: {
            name: 'Atlantic City International Airport',
            city: 'Atlantic City',
            state: 'NJ',
            country: 'United States',
            carriers: 1,
            flights: 6,
            tz: 'America/New_York',
            lat: 39.45759964,
            lon: -74.57720184
        },
        ALB: {
            name: 'Albany International Airport',
            city: 'Albany',
            state: 'NY',
            country: 'United States',
            carriers: 27,
            flights: 27,
            tz: 'America/New_York',
            lat: 42.74829865,
            lon: -73.80169678
        },
        AUS: {
            name: 'Austin Bergstrom International Airport',
            city: 'Austin',
            state: 'TX',
            country: 'United States',
            carriers: 37,
            flights: 50,
            tz: 'America/Chicago',
            lat: 30.19449997,
            lon: -97.66989899
        },
        AZO: {
            name: 'Kalamazoo Battle Creek International Airport',
            city: 'Kalamazoo',
            state: 'MI',
            country: 'United States',
            carriers: 12,
            flights: 5,
            tz: 'America/New_York',
            lat: 42.23490143,
            lon: -85.55210114
        },
        BDL: {
            name: 'Bradley International Airport',
            city: 'Windsor Locks',
            state: 'CT',
            country: 'United States',
            carriers: 31,
            flights: 41,
            tz: 'America/New_York',
            lat: 41.93889999,
            lon: -72.68319702
        },
        BFL: {
            name: 'Meadows Field',
            city: 'Bakersfield',
            state: 'CA',
            country: 'United States',
            carriers: 3,
            flights: 4,
            tz: 'America/Los_Angeles',
            lat: 35.43360138,
            lon: -119.0569992
        },
        BIS: {
            name: 'Bismarck Municipal Airport',
            city: 'Bismarck',
            state: 'ND',
            country: 'United States',
            carriers: 8,
            flights: 5,
            tz: 'America/Chicago',
            lat: 46.77270126,
            lon: -100.7460022
        },
        BRD: {
            name: 'Brainerd Lakes Regional Airport',
            city: 'Brainerd',
            state: 'MN',
            country: 'United States',
            carriers: 3,
            flights: 2,
            tz: 'America/Chicago',
            lat: 46.39830017,
            lon: -94.13809967
        },
        BUF: {
            name: 'Buffalo Niagara International Airport',
            city: 'Buffalo',
            state: 'NY',
            country: 'United States',
            carriers: 30,
            flights: 29,
            tz: 'America/New_York',
            lat: 42.94049835,
            lon: -78.73220062
        },
        BWI: {
            name: 'Baltimore/Washington International Thurgood Marshall Airport',
            city: 'Baltimore',
            state: 'MD',
            country: 'United States',
            carriers: 39,
            flights: 79,
            tz: 'America/New_York',
            lat: 39.17539978,
            lon: -76.66829681
        },
        CAE: {
            name: 'Columbia Metropolitan Airport',
            city: 'Columbia',
            state: 'SC',
            country: 'United States',
            carriers: 26,
            flights: 20,
            tz: 'America/New_York',
            lat: 33.93880081,
            lon: -81.11949921
        },
        CDC: {
            name: 'Cedar City Regional Airport',
            city: 'Cedar City',
            state: 'UT',
            country: 'United States',
            carriers: 1,
            flights: 1,
            tz: 'America/Denver',
            lat: 37.70100021,
            lon: -113.098999
        },
        CDV: {
            name: 'Merle K (Mudhole) Smith Airport',
            city: 'Cordova',
            state: 'AK',
            country: 'United States',
            carriers: 5,
            flights: 3,
            tz: 'America/Anchorage',
            lat: 60.4917984,
            lon: -145.4779968
        },
        CHA: {
            name: 'Lovell Field',
            city: 'Chattanooga',
            state: 'TN',
            country: 'United States',
            carriers: 15,
            flights: 13,
            tz: 'America/New_York',
            lat: 35.03530121,
            lon: -85.20379639
        },
        CMH: {
            name: 'Port Columbus International Airport',
            city: 'Columbus',
            state: 'OH',
            country: 'United States',
            carriers: 35,
            flights: 41,
            tz: 'America/New_York',
            lat: 39.9980011,
            lon: -82.89189911
        },
        CWA: {
            name: 'Central Wisconsin Airport',
            city: 'Wassau',
            state: 'WI',
            country: 'United States',
            carriers: 9,
            flights: 4,
            tz: 'America/Chicago',
            lat: 44.77759933,
            lon: -89.66680145
        },
        DAL: {
            name: 'Dallas Love Field',
            city: 'Dallas',
            state: 'TX',
            country: 'United States',
            carriers: 8,
            flights: 19,
            tz: 'America/Chicago',
            lat: 32.8470993,
            lon: -96.85179901
        },
        DCA: {
            name: 'Ronald Reagan Washington National Airport',
            city: 'Washington',
            state: 'VA',
            country: 'United States',
            carriers: 42,
            flights: 77,
            tz: 'America/New_York',
            lat: 38.8521,
            lon: -77.037697
        },
        DFW: {
            name: 'Dallas Fort Worth International Airport',
            city: 'Dallas-Fort Worth',
            state: 'TX',
            country: 'United States',
            carriers: 62,
            flights: 179,
            tz: 'America/Chicago',
            lat: 32.89680099,
            lon: -97.03800201
        },
        DLH: {
            name: 'Duluth International Airport',
            city: 'Duluth',
            state: 'MN',
            country: 'United States',
            carriers: 7,
            flights: 4,
            tz: 'America/Chicago',
            lat: 46.84209824,
            lon: -92.19360352
        },
        DRO: {
            name: 'Durango La Plata County Airport',
            city: 'Durango',
            state: 'CO',
            country: 'United States',
            carriers: 5,
            flights: 3,
            tz: 'America/Denver',
            lat: 37.1515007,
            lon: -107.7539978
        },
        ESC: {
            name: 'Delta County Airport',
            city: 'Escanaba',
            state: 'MI',
            country: 'United States',
            carriers: 2,
            flights: 2,
            tz: 'America/New_York',
            lat: 45.72269821,
            lon: -87.09369659
        },
        EUG: {
            name: 'Mahlon Sweet Field',
            city: 'Eugene',
            state: 'OR',
            country: 'United States',
            carriers: 15,
            flights: 12,
            tz: 'America/Los_Angeles',
            lat: 44.12459946,
            lon: -123.211998
        },
        GCK: {
            name: 'Garden City Regional Airport',
            city: 'Garden City',
            state: 'KS',
            country: 'United States',
            carriers: 3,
            flights: 4,
            tz: 'America/Chicago',
            lat: 37.92750168,
            lon: -100.723999
        },
        GEG: {
            name: 'Spokane International Airport',
            city: 'Spokane',
            state: 'WA',
            country: 'United States',
            carriers: 20,
            flights: 15,
            tz: 'America/Los_Angeles',
            lat: 47.61989975,
            lon: -117.5339966
        },
        GSP: {
            name: 'Greenville Spartanburg International Airport',
            city: 'Greenville',
            state: 'SC',
            country: 'United States',
            carriers: 25,
            flights: 25,
            tz: 'America/New_York',
            lat: 34.89569855,
            lon: -82.21890259
        },
        GUC: {
            name: 'Gunnison Crested Butte Regional Airport',
            city: 'Gunnison',
            state: 'CO',
            country: 'United States',
            carriers: 4,
            flights: 5,
            tz: 'America/Denver',
            lat: 38.53390121,
            lon: -106.9329987
        },
        HNL: {
            name: 'Honolulu International Airport',
            city: 'Honolulu',
            state: 'HI',
            country: 'United States',
            carriers: 36,
            flights: 43,
            tz: 'Pacific/Honolulu',
            lat: 21.31870079,
            lon: -157.9219971
        },
        HSV: {
            name: 'Huntsville International Carl T Jones Field',
            city: 'Huntsville',
            state: 'AL',
            country: 'United States',
            carriers: 24,
            flights: 17,
            tz: 'America/Chicago',
            lat: 34.6371994,
            lon: -86.77510071
        },
        IAD: {
            name: 'Washington Dulles International Airport',
            city: 'Washington',
            state: 'VA',
            country: 'United States',
            carriers: 63,
            flights: 150,
            tz: 'America/New_York',
            lat: 38.94449997,
            lon: -77.45580292
        },
        IAH: {
            name: 'George Bush Intercontinental Houston Airport',
            city: 'Houston',
            state: 'TX',
            country: 'United States',
            carriers: 54,
            flights: 210,
            tz: 'America/Chicago',
            lat: 29.9843998,
            lon: -95.34140015
        },
        INL: {
            name: 'Falls International Airport',
            city: 'International Falls',
            state: 'MN',
            country: 'United States',
            carriers: 3,
            flights: 1,
            tz: 'America/Chicago',
            lat: 48.56620026,
            lon: -93.40309906
        },
        ITO: {
            name: 'Hilo International Airport',
            city: 'Hilo',
            state: 'HI',
            country: 'United States',
            carriers: 9,
            flights: 3,
            tz: 'Pacific/Honolulu',
            lat: 19.72139931,
            lon: -155.0480042
        },
        JAX: {
            name: 'Jacksonville International Airport',
            city: 'Jacksonville',
            state: 'FL',
            country: 'United States',
            carriers: 31,
            flights: 32,
            tz: 'America/New_York',
            lat: 30.49410057,
            lon: -81.68789673
        },
        JLN: {
            name: 'Joplin Regional Airport',
            city: 'Joplin',
            state: 'MO',
            country: 'United States',
            carriers: 1,
            flights: 1,
            tz: 'America/Chicago',
            lat: 37.15179825,
            lon: -94.49829865
        },
        KOA: {
            name: 'Kona International At Keahole Airport',
            city: 'Kona',
            state: 'HI',
            country: 'United States',
            carriers: 17,
            flights: 11,
            tz: 'Pacific/Honolulu',
            lat: 19.73880005,
            lon: -156.0460052
        },
        KTN: {
            name: 'Ketchikan International Airport',
            city: 'Ketchikan',
            state: 'AK',
            country: 'United States',
            carriers: 11,
            flights: 13,
            tz: 'America/Anchorage',
            lat: 55.35559845,
            lon: -131.7140045
        },
        LAX: {
            name: 'Los Angeles International Airport',
            city: 'Los Angeles',
            state: 'CA',
            country: 'United States',
            carriers: 99,
            flights: 200,
            tz: 'America/Los_Angeles',
            lat: 33.94250107,
            lon: -118.4079971
        },
        LFT: {
            name: 'Lafayette Regional Airport',
            city: 'Lafayette',
            state: 'LA',
            country: 'United States',
            carriers: 9,
            flights: 5,
            tz: 'America/Chicago',
            lat: 30.20529938,
            lon: -91.98760223
        },
        LGB: {
            name: 'Long Beach /Daugherty Field/ Airport',
            city: 'Long Beach',
            state: 'CA',
            country: 'United States',
            carriers: 8,
            flights: 19,
            tz: 'America/Los_Angeles',
            lat: 33.81769943,
            lon: -118.1520004
        },
        LRD: {
            name: 'Laredo International Airport',
            city: 'Laredo',
            state: 'TX',
            country: 'United States',
            carriers: 15,
            flights: 13,
            tz: 'America/Chicago',
            lat: 27.54380035,
            lon: -99.46160126
        },
        MCO: {
            name: 'Orlando International Airport',
            city: 'Orlando',
            state: 'FL',
            country: 'United States',
            carriers: 63,
            flights: 106,
            tz: 'America/New_York',
            lat: 28.42939949,
            lon: -81.30899811
        },
        MDT: {
            name: 'Harrisburg International Airport',
            city: 'Harrisburg',
            state: 'PA',
            country: 'United States',
            carriers: 22,
            flights: 18,
            tz: 'America/New_York',
            lat: 40.19350052,
            lon: -76.76339722
        },
        MHK: {
            name: 'Manhattan Regional Airport',
            city: 'Manhattan',
            state: 'KS',
            country: 'United States',
            carriers: 3,
            flights: 5,
            tz: 'America/Chicago',
            lat: 39.14099884,
            lon: -96.67079926
        },
        MIA: {
            name: 'Miami International Airport',
            city: 'Miami',
            state: 'FL',
            country: 'United States',
            carriers: 91,
            flights: 167,
            tz: 'America/New_York',
            lat: 25.79319954,
            lon: -80.29060364
        },
        MOB: {
            name: 'Mobile Regional Airport',
            city: 'Mobile',
            state: 'AL',
            country: 'United States',
            carriers: 15,
            flights: 11,
            tz: 'America/Chicago',
            lat: 30.69120026,
            lon: -88.24279785
        },
        MRY: {
            name: 'Monterey Peninsula Airport',
            city: 'Monterey',
            state: 'CA',
            country: 'United States',
            carriers: 15,
            flights: 8,
            tz: 'America/Los_Angeles',
            lat: 36.5870018,
            lon: -121.8430023
        },
        MSO: {
            name: 'Missoula International Airport',
            city: 'Missoula',
            state: 'MT',
            country: 'United States',
            carriers: 11,
            flights: 8,
            tz: 'America/Denver',
            lat: 46.91630173,
            lon: -114.0910034
        },
        OMA: {
            name: 'Eppley Airfield',
            city: 'Omaha',
            state: 'NE',
            country: 'United States',
            carriers: 32,
            flights: 24,
            tz: 'America/Chicago',
            lat: 41.30319977,
            lon: -95.89409637
        },
        OME: {
            name: 'Nome Airport',
            city: 'Nome',
            state: 'AK',
            country: 'United States',
            carriers: 8,
            flights: 16,
            tz: 'America/Anchorage',
            lat: 64.5121994,
            lon: -165.4450073
        },
        ONT: {
            name: 'Ontario International Airport',
            city: 'Ontario',
            state: 'CA',
            country: 'United States',
            carriers: 17,
            flights: 29,
            tz: 'America/Los_Angeles',
            lat: 34.05599976,
            lon: -117.6009979
        },
        ORD: {
            name: 'Chicago O\'Hare International Airport',
            city: 'Chicago',
            state: 'IL',
            country: 'United States',
            carriers: 85,
            flights: 222,
            tz: 'America/Chicago',
            lat: 41.97859955,
            lon: -87.90480042
        },
        OTH: {
            name: 'Southwest Oregon Regional Airport',
            city: 'North Bend',
            state: 'OR',
            country: 'United States',
            carriers: 5,
            flights: 2,
            tz: 'America/Los_Angeles',
            lat: 43.417099,
            lon: -124.2460022
        },
        PAH: {
            name: 'Barkley Regional Airport',
            city: 'PADUCAH',
            state: 'KY',
            country: 'United States',
            carriers: 3,
            flights: 1,
            tz: 'America/Chicago',
            lat: 37.06079865,
            lon: -88.77380371
        },
        PDX: {
            name: 'Portland International Airport',
            city: 'Portland',
            state: 'OR',
            country: 'United States',
            carriers: 43,
            flights: 74,
            tz: 'America/Los_Angeles',
            lat: 45.58869934,
            lon: -122.5979996
        },
        PHF: {
            name: 'Newport News Williamsburg International Airport',
            city: 'Newport News',
            state: 'VA',
            country: 'United States',
            carriers: 6,
            flights: 7,
            tz: 'America/New_York',
            lat: 37.13190079,
            lon: -76.49299622
        },
        PIA: {
            name: 'General Wayne A. Downing Peoria International Airport',
            city: 'Peoria',
            state: 'IL',
            country: 'United States',
            carriers: 14,
            flights: 9,
            tz: 'America/Chicago',
            lat: 40.66419983,
            lon: -89.69329834
        },
        PIT: {
            name: 'Pittsburgh International Airport',
            city: 'Pittsburgh',
            state: 'PA',
            country: 'United States',
            carriers: 50,
            flights: 45,
            tz: 'America/New_York',
            lat: 40.49150085,
            lon: -80.23290253
        },
        PLN: {
            name: 'Pellston Regional Airport of Emmet County Airport',
            city: 'Pellston',
            state: 'MI',
            country: 'United States',
            carriers: 4,
            flights: 2,
            tz: 'America/New_York',
            lat: 45.57089996,
            lon: -84.79669952
        },
        PPG: {
            name: 'Pago Pago International Airport',
            city: 'Pago Pago',
            state: 'AS',
            country: 'American Samoa',
            carriers: 2,
            flights: 2,
            tz: 'Pacific/Pago_Pago',
            lat: -14.33100033,
            lon: -170.7100067
        },
        PVD: {
            name: 'Theodore Francis Green State Airport',
            city: 'Providence',
            state: 'RI',
            country: 'United States',
            carriers: 24,
            flights: 25,
            tz: 'America/New_York',
            lat: 41.73260117,
            lon: -71.42040253
        },
        SAT: {
            name: 'San Antonio International Airport',
            city: 'San Antonio',
            state: 'TX',
            country: 'United States',
            carriers: 34,
            flights: 44,
            tz: 'America/Chicago',
            lat: 29.53370094,
            lon: -98.46980286
        },
        SEA: {
            name: 'Seattle Tacoma International Airport',
            city: 'Seattle',
            state: 'WA',
            country: 'United States',
            carriers: 59,
            flights: 109,
            tz: 'America/Los_Angeles',
            lat: 47.44900131,
            lon: -122.3089981
        },
        SJC: {
            name: 'Norman Y. Mineta San Jose International Airport',
            city: 'San Jose',
            state: 'CA',
            country: 'United States',
            carriers: 33,
            flights: 34,
            tz: 'America/Los_Angeles',
            lat: 37.36259842,
            lon: -121.9290009
        },
        SLC: {
            name: 'Salt Lake City International Airport',
            city: 'Salt Lake City',
            state: 'UT',
            country: 'United States',
            carriers: 38,
            flights: 104,
            tz: 'America/Denver',
            lat: 40.78839874,
            lon: -111.9779968
        },
        SMF: {
            name: 'Sacramento International Airport',
            city: 'Sacramento',
            state: 'CA',
            country: 'United States',
            carriers: 29,
            flights: 37,
            tz: 'America/Los_Angeles',
            lat: 38.69540024,
            lon: -121.5910034
        },
        SNA: {
            name: 'John Wayne Airport-Orange County Airport',
            city: 'Santa Ana',
            state: 'CA',
            country: 'United States',
            carriers: 21,
            flights: 19,
            tz: 'America/Los_Angeles',
            lat: 33.67570114,
            lon: -117.8679962
        },
        TLH: {
            name: 'Tallahassee Regional Airport',
            city: 'Tallahassee',
            state: 'FL',
            country: 'United States',
            carriers: 10,
            flights: 10,
            tz: 'America/New_York',
            lat: 30.39649963,
            lon: -84.35030365
        },
        TOL: {
            name: 'Toledo Express Airport',
            city: 'Toledo',
            state: 'OH',
            country: 'United States',
            carriers: 17,
            flights: 56,
            tz: 'America/New_York',
            lat: 41.58679962,
            lon: -83.80780029
        },
        TYS: {
            name: 'McGhee Tyson Airport',
            city: 'Knoxville',
            state: 'TN',
            country: 'United States',
            carriers: 25,
            flights: 25,
            tz: 'America/New_York',
            lat: 35.81100082,
            lon: -83.9940033
        },
        VPS: {
            name: 'Destin-Ft Walton Beach Airport',
            city: 'Valparaiso',
            state: 'FL',
            country: 'United States',
            carriers: 12,
            flights: 8,
            tz: 'America/Chicago',
            lat: 30.4832,
            lon: -86.525398
        },
        YAK: {
            name: 'Yakutat Airport',
            city: 'Yakutat',
            state: 'AK',
            country: 'United States',
            carriers: 3,
            flights: 2,
            tz: 'America/Anchorage',
            lat: 59.50329971,
            lon: -139.6600037
        },

    };

export default airports;
